// <auto-generated />
using EmployeeVacationDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeVacationDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910143850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EmployeeVacationDB.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDaysWorked")
                        .HasColumnType("INTEGER");

                    b.Property<float>("VacationDaysUsed")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("EmployeeType").HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EmployeeVacationDB.Models.HourlyEmployee", b =>
                {
                    b.HasBaseType("EmployeeVacationDB.Models.Employee");

                    b.HasDiscriminator().HasValue("Hourly");
                });

            modelBuilder.Entity("EmployeeVacationDB.Models.SalariedEmployee", b =>
                {
                    b.HasBaseType("EmployeeVacationDB.Models.Employee");

                    b.HasDiscriminator().HasValue("Salaried");
                });

            modelBuilder.Entity("EmployeeVacationDB.Models.Manager", b =>
                {
                    b.HasBaseType("EmployeeVacationDB.Models.SalariedEmployee");

                    b.HasDiscriminator().HasValue("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
